/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.esg.mongodemo;

import static org.bson.codecs.configuration.CodecRegistries.fromProviders;
import static org.bson.codecs.configuration.CodecRegistries.fromRegistries;

import java.util.Optional;

import org.bson.codecs.configuration.CodecRegistry;
import org.bson.codecs.pojo.PojoCodecProvider;

import com.mongodb.MongoClientSettings;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;

public class Library
{
	private final String host = "localhost";
	private final int port = 27017;

	private MongoClient mongoClient;

	public void connectToServer()
	{
		try
		{
			final CodecRegistry pojoCodecRegistry = fromRegistries(com.mongodb.MongoClient.getDefaultCodecRegistry(),
					fromProviders(PojoCodecProvider.builder().automatic(true).build()));

			final MongoClientSettings settings = MongoClientSettings.builder().codecRegistry(pojoCodecRegistry).build();
			this.mongoClient = MongoClients.create(settings);
		}
		catch (final Exception e)
		{
			e.printStackTrace();
		}
	}

	public void disconnectFromServer()
	{
		Optional.of(this.mongoClient).ifPresent(client -> client.close());
	}

	public void createProject(final Project project)
	{
		final MongoDatabase database = this.mongoClient.getDatabase("projectDb");
		final MongoCollection<Project> collection = database.getCollection("projects", Project.class);

		collection.insertOne(project);

	}

	public Project getFirstProject()
	{
		final MongoDatabase database = this.mongoClient.getDatabase("projectDb");
		final MongoCollection<Project> collection = database.getCollection("projects", Project.class);

		final Project result = collection.find().first();
		return result;
	}

	public long getCountProject()
	{
		final MongoDatabase database = this.mongoClient.getDatabase("projectDb");
		final MongoCollection<Project> collection = database.getCollection("projects", Project.class);

		final long result = collection.countDocuments();
		return result;
	}

}
