version: '3.7'

services:
 mongodb:
  image: mongo:4.0.4
  container_name: mongodb
  ports:
  - "27017:27017"
  network_mode: "mynet"
  
 mongoexpress:
  image: mongo-express:latest
  container_name: mongoexpress
  ports:
  - "8282:8081"
  environment:
    ME_CONFIG_MONGODB_SERVER: mongodb
  depends_on:
     - mongodb  
  network_mode: "mynet"
 
  
 