/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.esg.mongodemo;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

// externer docker container 
public class LibraryTestExtDC
{

	Library classUnderTest = new Library();

	@Test
	public void testCreateProject()
	{
		// act
		final Project project = this.classUnderTest.createProject();

		// assert
		assertNotNull(project);

		System.out.println(project.toString());

	}
}
